### ISSUE TITLE
BBS 3.2 (the current version) has issues related to the 'rgl' package on Windows

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#1]
In reviewing the build report today, I noticed that the package `ampliQueso` is failing to build on Windows : http://bioconductor.org/checkResults/devel/bioc-LATEST/ampliQueso/windows1.bioconductor.org-checksrc.html .  

I've discussed this failure with @dtenenba and he advised me that this appears to be a bug with the build system.  Based on previously seen issues, sometimes the build system reinstalls `rgl` from source and "_builds binaries for only on one architecture_" (presumably `x64` in this case). By reinstalling the binary version of `rgl` on `i386` the build errors with the `ampliQueso` package will go away.  

### TODO
We need to determine what causes the `rgl` to be reinstalled and upon this reinstallation why binaries for `x64` are not included.

### Summary

```shell
Package: ampliQueso
Version: 1.7.0
Command: rm -rf ampliQueso.buildbin-libdir ampliQueso.Rcheck && mkdir ampliQueso.buildbin-libdir ampliQueso.Rcheck && C:\biocbld\bbs-3.2-bioc\R\bin\R.exe CMD INSTALL --build --merge-multiarch --library=ampliQueso.buildbin-libdir ampliQueso_1.7.0.tar.gz >ampliQueso.Rcheck\00install.out 2>&1 && cp ampliQueso.Rcheck\00install.out ampliQueso-install.out && C:\biocbld\bbs-3.2-bioc\R\bin\R.exe CMD check --library=ampliQueso.buildbin-libdir --install="check:ampliQueso-install.out" --force-multiarch --no-vignettes --timings ampliQueso_1.7.0.tar.gz
StartedAt: 2015-09-21 23:44:44 -0400 (Mon, 21 Sep 2015)
EndedAt: 2015-09-21 23:44:51 -0400 (Mon, 21 Sep 2015)
EllapsedTime: 7.2 seconds
RetCode: 1
Status:  ERROR  
CheckDir: ampliQueso.Rcheck
Warnings: NA
```
### Command output

```shell
##############################################################################
##############################################################################
###
### Running command:
###
###   rm -rf ampliQueso.buildbin-libdir ampliQueso.Rcheck && mkdir ampliQueso.buildbin-libdir ampliQueso.Rcheck && C:\biocbld\bbs-3.2-bioc\R\bin\R.exe CMD INSTALL --build --merge-multiarch --library=ampliQueso.buildbin-libdir ampliQueso_1.7.0.tar.gz >ampliQueso.Rcheck\00install.out 2>&1 && cp ampliQueso.Rcheck\00install.out ampliQueso-install.out  && C:\biocbld\bbs-3.2-bioc\R\bin\R.exe CMD check --library=ampliQueso.buildbin-libdir --install="check:ampliQueso-install.out" --force-multiarch --no-vignettes --timings ampliQueso_1.7.0.tar.gz
###
##############################################################################
##############################################################################

```
ampliQueso.Rcheck/00install.out:

```shell
install for i386

* installing *source* package 'ampliQueso' ...
** R
** data
** inst
** preparing package for lazy loading
Error : package 'rgl' is not installed for 'arch = i386'
ERROR: lazy loading failed for package 'ampliQueso'
* removing 'C:/biocbld/bbs-3.2-bioc/meat/ampliQueso.buildbin-libdir/ampliQueso'
Warning: running command 'C:/biocbld/bbs-3.2-bioc/R/bin/i386/Rcmd.exe INSTALL --library=ampliQueso.buildbin-libdir ampliQueso_1.7.0.tar.gz --no-multiarch' had status 1
```

**Comment by b-long** [comment]
For the purposes of documenting this issue.  Please note that the 'rgl' bug aslo affects the following packages (and likely more outside of my package range) : 

- a4
- a4Classif
- ampliQueso
- arrayMvout
- beadarray
- BubbleTree
- ChAMP

**Comment by dtenenba** [comment]
Packages installed from source by the build system should be installed with the `--merge-multiarch` flag on windows. That ought to fix this.

**Comment by federicomarini** [comment]
Hi Dan,

I just noticed I am also affected with my package flowcatchR by this issue. You mentioned in the bioc-devel mailing list on Sep 23 that it should be gone, but I realized it is still on.
Will it affect anything with the upcoming bioc release?

**Comment by dtenenba** [comment]
It was gone but it came back. It's a bug that shows up when certain packages are updated and their source version is newer than the binary version. It will NOT affect anything with the release.

**Comment by b-long** [comment]
Fixed by https://github.com/Bioconductor/BBS/commit/9c3c25dc632bf87c4c40f02f4a42c1d81938e4d9 .
