### ISSUE TITLE
Automate daily tasks

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#11]
Currently, the BBS has to be checked daily for failures.  Instead, the system should be made more robust , and any daily tests should be automated.  This issue will serve as a grouping of several issues which need to be resolved in order to move forward with automation.

Current blockers include : 
- [Document & automate usage of special directories](https://github.com/Bioconductor/BBS/issues/9)
- [Jobs sometimes do not timeout](https://github.com/Bioconductor/BBS/issues/7)

**Comment by b-long** [comment]
Created [setup-environment.sh](https://github.com/Bioconductor/bioc-cm) to help solve this problem.  By knowing the machine's hostname &  Bioconductor versions, we can dynamically determine the resources to inspect on a node.  Also, components can source `setup-environment.sh` at startup and use the exported environment variables.  This will allow us to replace hardcoded strings like the ones in this commit (https://github.com/Bioconductor/packagebuilder/commit/b6578785069369a8b9b2721a0de0f761c8f22479) with strings we get dynamically.  The script ["setup-environment.sh"](https://github.com/Bioconductor/bioc-cm) is a work in progress and currently only supports a subset of the Bioconductor infrastructure nodes.

Please feel free to comment on this offer suggestions.  One thing to note is that we'll need to support Windows infrastructure as well.  

/cc @dtenenba @jimhester Any thoughts?

**Comment by dtenenba** [comment]
Nice. config.yaml should be sourced from http://master.bioconductor.org/config.yaml instead of from github. This is the canonical location that will reflect updates most quickly. The github location is not automatically synced with svn.

**Comment by b-long** [comment]
Good catch, thanks @dtenenba !

**Comment by vobencha** [comment]
Issue is outdated. Automating daily monitoring of the build system is not a current priority.
