### ISSUE TITLE
crontab for biocbuild has hardcoded paths

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#13]
The `crontab` for the biocbuild user has hardcoded paths.  This has the following side-effects : 
- The crontab for each Linux controller is different (e.g. 3.2 vs 3.3 builds)
- Commands executed by cron are very long
- The crontab must be manually adjusted each time we perform a release
- Manually adjusting files often results in mistakes
- `crontab` includes configuration not in source control

Here's a snippet of the `crontab` from biocbuild@linux2 : 

```
# kill all R processes that have run for too long
10 * * * * /usr/bin/python /home/biocbuild/BBS/utils/killproc.py >> /home/biocbuild/bbs-3.3-bioc/log/killproc.log 2>&1

# weekly kill of all processes belonging to biocbuild
####15 20 * * 0 kill -9 -1 > /dev/null 2>&1

# bbs-3.3-bioc
20 20 * * * cd /home/biocbuild/BBS/3.3/bioc/linux2.bioconductor.org && ./prerun.sh >>/home/biocbuild/bbs-3.3-bioc/log/linux2.bioconductor.org.log 2>&1
00 21 * * * /bin/bash --login -c 'cd /home/biocbuild/BBS/3.3/bioc/linux2.bioconductor.org && ./run.sh >>/home/biocbuild/bbs-3.3-bioc/log/linux2.bioconductor.org.log 2>&1'
# IMPORTANT: Make sure this is started AFTER 'biocbuild' has finished its "run.sh" job on ALL other nodes!
05 12 * * * cd /home/biocbuild/BBS/3.3/bioc/linux2.bioconductor.org && ./postrun.sh >>/home/biocbuild/bbs-3.3-bioc/log/linux2.bioconductor.org.log 2>&1

# bbs-3.3-data-experiment
15 10 * * 3,6 cd /home/biocbuild/BBS/3.3/data-experiment/linux2.bioconductor.org && ./prerun.sh >>/home/biocbuild/bbs-3.3-data-experiment/log/linux2.bioconductor.org.log 2>&1
55 10 * * 3,6 /bin/bash --login -c 'cd /home/biocbuild/BBS/3.3/data-experiment/linux2.bioconductor.org && ./run.sh >>/home/biocbuild/bbs-3.3-data-experiment/log/linux2.bioconductor.org.log 2>&1'
# IMPORTANT: Make sure this is started AFTER 'biocbuild' has finished its "run.sh" job on ALL other nodes!
55 18 * * 3,6 cd /home/biocbuild/BBS/3.3/data-experiment/linux2.bioconductor.org && ./postrun.sh >>/home/biocbuild/bbs-3.3-data-experiment/log/linux2.bioconductor.org.log 2>&1
```

To improve upon the current `crontab`, I recommend the following actions : 

1) Create a wrapper script for each command in the cron 
2) The wrapper script will source environment variables, as defined by [bioc-cm](https://github.com/Bioconductor/bioc-cm) (environment variables can also be used in the crontab).
3) If specific paths are needed by cron and they do not exist in `bioc-cm`, submit a Pull Request to include such paths as environment variables
4) Version control all wrapper scripts
5) Test all wrapper scripts using some tooling (_docker_ locally?  Follow [this](https://travis-ci.org/Bioconductor/bioc-cm) example for linting scripts).
6) As much as it is possible, use the same crontab across servers.  Consider replacing the following line : 

```
20 20 * * * cd /home/biocbuild/BBS/3.3/bioc/linux2.bioconductor.org && ./prerun.sh >>/home/biocbuild/bbs-3.3-bioc/log/linux2.bioconductor.org.log 2>&1
```

  with something like : 

```
20 20 * * * . ~/bioc-cm/setup-environment.sh; executePrerun.sh
```

cc/ @dtenenba @jimhester Please comment.

Improvements like this will also move us towards the goal of further automation (https://github.com/Bioconductor/BBS/issues/11) and eliminating  [DailyTasks.md](https://github.com/bioconductor/BBS/blob/master/Doc/DailyTasks.md)

**Comment by hpages** [comment]
hardcoded paths in the crontabs are a feature, not a bug
