### ISSUE TITLE
colors of builders in 3.16

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#142]
Hi @jwokaty ,

Do you think we can keep the usual colors for the builders in 3.16? These colors reflect the OS (blue for Linux, red for Windows, and green for macOS). Changing this means we need to learn a new scheme. The idea is to be able to immediately recognize what platform we are looking at and so sticking to a fixed scheme helps avoid confusion.

Thanks,
H.

**Comment by jwokaty** [comment]
So I should change the color of palomino4 to a reddish color and that will satisfy your request? (I didn't notice there a pattern, sorry.)

**Comment by hpages** [comment]
yes, same color as palomino3, thx!

**Comment by hpages** [comment]
I took care of this
