### ISSUE TITLE
Windows Doc should use Ubuntu pip file

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#144]

**Comment by hpages** [comment]
Nice move @jwokaty. This significantly reduces repetition across the 3 main `Prepare-*-HOWTO.md` documents and helps with automation. Thanks!

On the removal of the TESTING section:

Isn't it nice to be able to quickly validate our work by running a simple one-liner? That's what these little TESTING sections are for. The code snippets they provide (+ the troubleshooting tips associated with them) are often the result of some bitter past experiences, and the goal is to hopefully prevent anybody in charge of managing the build machines from going thru the pain again. :wink:

However, I can also see the value of keeping the documentation clean, short, current, accurate, focused, etc... So if you strongly believe that the `tensorflow` issue covered in this TESTING section is _very_ unlikely to happen again in the future, then so be it. However in this case, please note that the 2 original reasons for installing Visual Studio Community on the Windows builders are now gone (one was to get the `editbin` command, the other one to get some DLLs sometimes needed by the most recent versions of the `tensorflow` Python module). So there's no reason to keep the _Install Visual Studio Community 2022_ section around.

Thanks

**Comment by jwokaty** [comment]
I reverted my PR so that I can make another commit that keeps the testing section. However, it's not clear to me if you are saying that VS should be removed. When I read it last night, it sounded like it should be removed but reading it again, it sounds like it might be dependent on some situation. Can you clarify if VS should be removed?

**Comment by hpages** [comment]
Visual Studio Community would only be needed if the `import tensorflow` test failed in the way described in the doc.

Maybe that part could be slightly edited:
```
Provides the `editbin` command, plus some DLLs apparently needed by the
most recent versions of the `tensorflow` Python module.
```
e.g.:
```
Only needed if the `tensorflow` Python module fails to load. See _Install Python 3 modules_ section below.
```
Does this help?

**Comment by jwokaty** [comment]
Yes, thanks!
