### ISSUE TITLE
Investigate perceval build problems

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#15]
Mac Snow Leopard build machine at FHCRC  (perceval) has been failing to build for several days.  This machine was previously used in the current release of Bioconductor (3.2).  This must be triaged by someone with access to that network and/or physical server.

**Comment by b-long** [comment]
Ignore the mention of this bug in https://github.com/Bioconductor/BBS/commit/103a67b508d64f19f18c3770d66408a7b38d448a , that was in error.

**Comment by b-long** [comment]
We'll make one more effort to revive perceval.  If that fails, we plan to close this issue soon.

**Comment by vobencha** [comment]
perceval is no longer one of the build machines.
