### ISSUE TITLE
Propagate of M1 binaries - part 1: Make sure postrun.sh does the right thing

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#179]
Hi Jen,

Since the introduction of M1 binaries the basic layout of a CRAN-style package repo now looks like this:

    ├── bin
    │   ├── macosx
    │   │   ├── big-sur-arm64             #  new
    │   │   │   └── contrib               #  new
    │   │   │       └── 4.2               #  new
    │   │   │           └── PACKAGES      #  new
    │   │   └── contrib
    │   │       └── 4.2
    │   │           └── PACKAGES
    │   └── windows
    │       └── contrib
    │           └── 4.2
    │               └── PACKAGES
    └── src
        └── contrib
            └── PACKAGES

We will need to propagate the new M1 binaries to `bin/macosx/big-sur-arm64/contrib/4.2/`.

Let's focus on `postrun.sh` for now. `postrun.sh` does basically 4 things, in this order:
- Call `BBS-make-BUILD_STATUS_DB.py` to generate the _package build status database_ (`BUILD_STATUS_DB.txt`).
- Call `BBS-make-OUTGOING.py` to create and populate the `OUTGOING` folder.
- Call `BBS-make-PROPAGATION_STATUS_DB.py` to generate the _package propagation status database_ (`PROPAGATION_STATUS_DB.txt`).
- Call `BBS-report.py` to generate the HTML report. Note that the report will display little LEDs in the rightmost column to indicate the propagation status of each package (need to switch to the "Long report" to see them).

The focus of this issue is to make sure that all these things work properly for the M1 builds, and that we end up with a report showing the LEDS.

What needs to happen (in this order):

1. Fix `BBS-make-BUILD_STATUS_DB.py`. I could be wrong but I don't think that the script works right now for the M1 builds because I believe the script expects to see the results of the CHECK stage, which we don't run for the M1 builds.

2. Choose a name for the `OUTGOING` subfolder where the `postrun.sh` script will copy the M1 binaries produced by kjohnson. The `OUTGOING` folder is on the central builder (biocbuild account on nebbiolo2), under `~/public_html/BBS/3.16/bioc/`. Right now it has the following subfolders: `source`, `win.binary`, and `mac.binary`. Note that those exact names is our internal business so they don't need to match what CRAN is using for the layout of a CRAN-style package repo or to match the official `pkgType` used by `install.packages()` and family. We use these names when we set the `BBS_OUTGOING_MAP` variable to specify what to populate the `OUTGOING` subfolders with. For example this is what we use at the moment at the end of the daily devel builds:
    ```
    export BBS_OUTGOING_MAP="source:nebbiolo2/buildsrc win.binary:palomino4/buildbin mac.binary:lconway/buildbin"
    ```
    If we choose `OUTGOING/m1.binary` for where we're going to copy the M1 binaries produced by kjohnson, then we'll need to set `BBS_OUTGOING_MAP` as follow for the `bioc-m1` builds:
    ```
    export BBS_OUTGOING_MAP="m1.binary:kjohnson/buildbin"
    ```
    Then when you run the `postrun.sh` script at the end of the `bioc-m1` builds on nebbiolo2, the M1 binaries produced by kjohnson should end up in `OUTGOING/m1.binary/`. Note that the `BBS-make-OUTGOING.py` script actually does the job (it's called by `postrun.sh`). Try to run `postrun.sh` and see how it goes.

3. In the biocpush account (on nebbiolo2): create `~/PACKAGES/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/` with empty `PACKAGES` index file in it.

4. Fix `BBS-make-PROPAGATION_STATUS_DB.py`. The script looks at the content of `OUTGOING/source`, `OUTGOING/win.binary`, and `OUTGOING/mac.binary` (and also at other things, but they don't matter here) to infer the propagation status of source, Windows, and Intel Mac packages. It doesn't know about the new `OUTGOING/m1.binary` folder so needs to be modified.

5. Try to run `postrun.sh` and see how it goes. Did `BBS-make-PROPAGATION_STATUS_DB.py` do its job? Do we see LEDs on the report?

I've probably forgotten a few things, sorry, but that should get you started. Don't hesitate to ask below. I'll update/correct/complete the above as we go. Thanks!

**Comment by jwokaty** [comment]
I'm going to manually make the adjustments on kjohnson; however, I will put the commits associated with this to #172 .

**Comment by hpages** [comment]
Please take a look at https://github.com/Bioconductor/BBS/pull/172#issuecomment-1212527063 for what I think will be a better way to proceed. Don't hesitate to ask if you have questions/comments or need further clarifications. Thanks

**Comment by jwokaty** [comment]
@hpages I'm not sure what change you're expecting should be made for number 4 after looking at that file. Isn't the path passed to the function?

**Comment by hpages** [comment]
Maybe. I didn't take a close look at `BBS-make-PROPAGATION_STATUS_DB.py` in a while, was just speaking from memory. IIRC the script is a thin wrapper to an R function and all the work is actually done by that R function. I was under the impression that this R function would need to be modified to process the stuff in `OUTGOING/m1.binary` (or `OUTGOING/mac.arm64.binary`), but if you ran the script and it's doing the right thing already then great!

**Comment by hpages** [comment]
Nice to be able to close this :wink:

Now we need to work on the biocpush side of things. I'm going to provide some details about this in a new issue: "Propagate M1 binaries - part 2: biocpush scripts and crontab".

**Comment by hpages** [comment]
Here it is: https://github.com/Bioconductor/BBS/issues/186
