### ISSUE TITLE
Install Python module leidenalg on the builders

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#204]
Add `leiden` to the cran deps packages for scBubbletree if it is accepted into Bioconductor: https://github.com/Bioconductor/Contributions/issues/2781. It also requires `leidenalg`.

**Comment by hpages** [comment]
I'm confused, isn't CRAN package **leiden** already on all the build machines?

Besides we don't need to do anything to manage dependencies on CRAN packages. Those will be automatically installed by the build system granted that Bioconductor package developers have them listed in the `Depends`, `Imports`, or `Suggests` field of their package.

What we need to manually install on the build machines are the _external_ dependencies i.e. deps that are _not_ R packages. Those are the deps that package developers should list in their `SystemRequirements` field.

In this case, I think it's _Python module_ `leidenalg`, but let's wait confirmation from the **scBubbletree** submitter (also they will need to add a `SystemRequirements` field first).

**Comment by lshep** [comment]
They depend on Seurat , that depends on leiden, leiden has the python system dependencies and python module requirements.

**Comment by hpages** [comment]
Any chance you can install `leidenalg` on nebbiolo2 Jen? :smile:

**Comment by hpages** [comment]
Maybe you did, maybe I'm not using the right command:
```
biocbuild@nebbiolo2:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import leidenalg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'leidenalg'
>>> 
```

**Comment by jwokaty** [comment]
I pip3 installed it.

**Comment by hpages** [comment]
Any idea why I can't load the module?

**Comment by jwokaty** [comment]
I think you tried before it was installed. It loads now.

**Comment by hpages** [comment]
Still failing: https://github.com/Bioconductor/Contributions/issues/2781#issuecomment-1260053621

Are you installing this system-wide, as documented? All system deps need to be installed system-wide.

You should be able to start python3 and import `leidenalg` from any account. 

Please communicate with the **scBubbletree** submitter. Thanks!

**Comment by jwokaty** [comment]
Ok, that's probably what it is.

**Comment by snaketron** [comment]
Now that scBubbletree is accepted could you please install the Python module leidenalg 
on the other machines.

It is currently failing on lconway with the same error:

> Message: Cannot find Leiden algorithm, please install through pip (e.g. pip install leidenalg).

https://bioconductor.org/checkResults/3.16/bioc-LATEST/scBubbletree/

Thanks!

**Comment by jwokaty** [comment]
@snaketron Thanks for following up. It's installed on all devel machines. We should see how it fairs on the next build report.
