### ISSUE TITLE
Check for MiKTeX updates on Windows builders

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#207]
I've noticed that we started to see many "major issue: So far, you have not checked for updates as a MiKTeX user" messages recently on palomino4. Did you reinstall MiKTeX recently on the machine? If so, make sure to complete all the steps described here: https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-Windows-Server-2022-HOWTO.md#115-install-miktex Thx!

[1:10](https://devteam-bioc.slack.com/archives/D01UZSJH7DX/p1664817012818679)
An example of such message: https://bioconductor.org/checkResults/3.16/bioc-LATEST/hipathia/palomino4-buildsrc.html

**Comment by hpages** [comment]
The title of the issue is misleading. There's no reason a priori to reinstall MiKTeX on the palominos. The message we see on palomino4:

> major issue: So far, you have not checked for updates as a MiKTeX user

only suggests that MiKTeX updates were not checked after MiKTeX was reinstalled in August.

**Comment by jwokaty** [comment]
@hpages Thank you. How often did you usually check for MiKTeX updates?

Checked and ran updates on the Windows builders on Oct. 5, 2022. Wait to confirm issue resolved by checking https://bioconductor.org/checkResults/3.16/bioc-LATEST/hipathia/palomino4-buildsrc.html. We should not receive errors such as
```
!!! Error: Cannot call ghostscript `mgs' (No such file or directory/The system cannot find the file specified)!
pdfcrop: major issue: So far, you have not checked for updates as a MiKTeX user.
```

**Comment by hpages** [comment]
> How often did you usually check for MiKTeX updates?

Never. But we must do it at least once, right after we install MiKTeX. Otherwise MiKTeX complains and weird things happen :wink:
