### ISSUE TITLE
Coverage not running, or failing

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/BBS#22]
Code coverage is not working, the bash script at https://github.com/Bioconductor/BBS/blob/master/utils/compute_coverage.sh which runs R code at https://github.com/Bioconductor/BBS/blob/master/utils/compute_coverage.R needs to run.

Two environment variables need to be set
1. `CODECOV_TOKEN`
2. `GITHUB_OAUTH_TOKEN`

I can run the script manually, but we should figure out why they weren't running. I am guessing because the above environment variables are not set _or_ coverage was not added back to the crontabs when the build system moved back into the hutch.

**Comment by jimhester** [comment]
This is fixed for dev repos, but not for release?

**Comment by mtmorgan** [comment]
@jimhester is this issue addressed?

**Comment by dtenenba** [comment]
Part of this seems to be because timeouts in BiocParallel are not yet working if the code you are calling includes C code. So some packages whose unit tests run forever are causing the script to never return. I might change it temporarily to not run in parallel.

**Comment by mtmorgan** [comment]
Or control the length of the job outside R?

**Comment by dtenenba** [comment]
The way this is written, BiocParallel is used to run the coverage of N packages at once, (ideally) timing out after Y seconds. I'm not sure how I would control the length of the job outside R.

**Comment by vobencha** [comment]
Closing this issue as the coverage scripts are no longer run.
