### ISSUE TITLE
Add Python package 'packaging' to list of requirements, and install on all builders

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#226]
https://stat.ethz.ch/pipermail/bioc-devel/2022-October/019255.html

Looks like `packaging` is already on some builders but not on all of them: https://bioconductor.org/checkResults/3.16/bioc-LATEST/seqArchR/palomino4-checksrc.html

**Comment by jwokaty** [comment]
Adding for Bioc package seqArchR. They might remove this later in favor of using basilisk to manage Python dependencies.

**Comment by jwokaty** [comment]
Installed `packaging` on pal3 and pal4.
