### ISSUE TITLE
Remove BBS_STAGE2_MODE=multiarch

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#227]
From Slack:

> This crazy long and convoluted command is a leftover from when we used to install for the two archs, 32- and 64-bit. Installing directly from the source code didn't play well with that. There's a crazy long comment in the BBS code about this: https://github.com/Bioconductor/BBS/blob/1f1cfffeaf4ae726d5199c2eb90c19f39fce3906/BBSbase.py#L230-L253
> We need to get rid of this.
> We should remove the set BBS_STAGE2_MODE=multiarch lines from all the config.bat files on the palominos. Thx!

**Comment by jwokaty** [comment]
@hpages Should we remove this mode for all stages?

**Comment by hpages** [comment]
Yes, for all stages, for the 3.15 and 3.16 builds. Thanks

**Comment by hpages** [comment]
oh, but we've stopped the 3.15 builds already. Nevermind...
