### ISSUE TITLE
WISH: Check for forgotten package dependencies in package vignettes

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BBS#242]
For Bioconductor devel (3.17), please consider running checks with:

```
_R_CHECK_DEPENDS_ONLY_VIGNETTES_=true
```

This will make `R CMD check` check package vignettes in a sandboxed environment where the package library only holds packages that are declared as dependencies (and the dependencies of the dependencies, etc.).

PS. This requires a recent R-devel version, since there was a bug related to `_R_CHECK_DEPENDS_ONLY_VIGNETTES_` preventing this to work for vignettes.

# Example

For example, compare all `OK` results in <https://bioconductor.org/checkResults/devel/bioc-LATEST/MOSim/nebbiolo1-checksrc.html> with:

```sh
## Just to show that I don't have a ~/.R/check.Renviron in play
$ export R_CHECK_ENVIRON=non-existing

$_R_CHECK_DEPENDS_ONLY_VIGNETTES_=true R --vanilla CMD check MOSim_1.13.0.tar.gz 
* using log directory ‘/tmp/bioc/MOSim.Rcheck’
* using R Under development (unstable) (2022-11-13 r83341)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘MOSim/DESCRIPTION’ ... OK
* this is package ‘MOSim’ version ‘1.13.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ...
Warning: unable to access index for repository https://CRAN.R-project.org/src/contrib:
  cannot open URL 'https://CRAN.R-project.org/src/contrib/PACKAGES'

 OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘MOSim’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  5.1Mb
  sub-directories of 1Mb or more:
    data   4.2Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking sizes of PDF files under ‘inst/doc’ ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ...
 OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘MOSim.Rnw’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... ERROR
Error(s) in re-building vignettes:
  ...
--- re-building ‘MOSim.Rnw’ using knitr
Quitting from lines 8-10 (MOSim.Rnw) 
Error: processing vignette 'MOSim.Rnw' failed with diagnostics:
there is no package called 'BiocStyle'
--- failed re-building ‘MOSim.Rnw’

SUMMARY: processing the following file failed:
  ‘MOSim.Rnw’

Error: Vignette re-building failed.
Execution halted

* checking PDF version of manual ... OK
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 ERROR, 1 NOTE
```

# Expected outcome

From doing many revdep checks, I'd say the most common mistakes are to forget `Suggests: BiocStyle` and `Suggests: codetools`, but there are of course many others too.

**Comment by HenrikBengtsson** [comment]
Sample stats when checking Bioconductor packages with `_R_CHECK_DEPENDS_ONLY_VIGNETTES_=true`.  When running revdep **matrixStats**, there are 205 Bioconductor checked.  Out of these 205 packages, 15 packages (0.7%) fail _vignettes_ checks, because they're not declaring all packages needed as dependency.  The package are, with missing packages in parentheses:

* AMARETTO (BiocStyle)
* autonomics (BiocStyle)
* bigPint (BiocStyle)
* bnem (BiocStyle)
* DepInfeR (BiocStyle)
* disbayes (codetools)
* DMCFB (BiocStyle)
* mnem (BiocStyle)
* moanin (codetools)
* MOSim (codetools)
* nempi (BiocStyle)
* rADA (codetools)
* SCFA (BiocStyle)
* scmap (BiocStyle)
* tenXplore (BiocStyle)

Details: <https://github.com/HenrikBengtsson/matrixStats/blob/develop/revdep/problems.md>

**Comment by vjcitn** [comment]
I'm in agreement with all three wishes.  Do you have a sense of how much extra time is needed to get this information from the sandboxed runs?

**Comment by HenrikBengtsson** [comment]
Thanks for looking at this.

>  Do you have a sense of how much extra time is needed to get this information from the sandboxed runs?

I'm not sure I understand the question. Are you wondering about the extra overhead added for `R CMD check`?  If so, it'll be minimal, near zero.

**Comment by hpages** [comment]
Adding
```
_R_CHECK_DEPENDS_ONLY_VIGNETTES_=true
_R_CHECK_DEPENDS_ONLY_TESTS_=true
_R_CHECK_DEPENDS_ONLY_EXAMPLES_=true
```
to https://github.com/Bioconductor/BBS/blob/master/3.17/Renviron.bioc makes a lot of sense as long as this doesn't impact too much the running time of the daily builds.

Thanks

**Comment by HenrikBengtsson** [comment]
It won't add more processing time.

**Comment by hpages** [comment]
I always assumed that `R CMD check` was not checking these things because it was somehow too expensive to do so. But if it has not cost then why isn't this checked by default? Packages used in vignettes, tests, and examples must of course be declared as deps. Why is this check even optional?

**Comment by HenrikBengtsson** [comment]
Hold on ... I need to sleep on this one. I might have done a big thinko with these three feature requests. I'll sleep on it and report back tomorrow.

**Comment by HenrikBengtsson** [comment]
I made a mistake with #242, #243, and #244; closing them all, because they are way overkill.  

The intended feature request is `_R_CHECK_SUGGESTS_ONLY_=true` for all of them.  That is now explained in #248.

**Comment by hpages** [comment]
yep
