### ISSUE TITLE
fftw3 for Mac

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#256]
Depending on the acceptance of https://github.com/Bioconductor/Contributions/issues/2880, document install process for fftw3 on Mac (and possibly Windows), which is a sys req for CRAN package `qqconf` that is required by `metap` (a direct dependency). It seems to be already installed on linux, so we may still need to open an issue for docker so it can be checked.

**Comment by hpages** [comment]
The SPB uses R-devel but CRAN does not provide Mac binary packages for R-devel yet. Maybe it's just a matter of adding **qqconf** to the list of difficult packages? https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#what-if-cran-doesnt-provide-package-binaries-for-macos-yet

The situation is different on Windows: CRAN provides Windows binary packages for R-devel so we shouldn't need to install any external lib there. Also IIUC all external libs required for CRAN packages are now supposed to be bundled in Rtools so hopefully we won't need to install anything.

**Comment by lshep** [comment]
oops.  forgot about that point and we are in that cycle that we have to wait for the devel binaries.  thanks for the reminder!

**Comment by jwokaty** [comment]
Ok, we'll wait. If it becomes a time sensitive, this can be reopened.
