### ISSUE TITLE
Accomodate CRAN package redux

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#264]
@jwokaty 

Required by Bioconductor package **RedisParam** (Martin's).

- Linux builders: **redux** requires `libhiredis-dev` on Ubuntu:
```
> install.packages("redux")
trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/redux_1.1.3.tar.gz'
Content type 'application/x-gzip' length 97908 bytes (95 KB)
==================================================
downloaded 95 KB

* installing *source* package ‘redux’ ...
** package ‘redux’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/hiredis
Using PKG_LIBS=-lhiredis
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because hiredis was not found. Try installing:
 * deb: libhiredis-dev (Debian, Ubuntu, etc)
 * rpm: hiredis-devel (Fedora, EPEL)
 * brew: hiredis (OSX)
If hiredis is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a hiredis.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘redux’
* removing ‘/home/hpages/R/R-4.3.r83438/library/redux’

The downloaded source packages are in
	‘/tmp/RtmpMvarDX/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("redux") :
  installation of package ‘redux’ had non-zero exit status
```

- Windows builders: Nothing required there. CRAN always provides Windows binary packages for R release and devel (or at least they make a bin/windows/contrib/4.3 symlink that redirects to bin/windows/contrib/4.2).

- Mac builders (intel and arm64): CRAN provides no Mac binary packages (intel or arm64) for R devel at the moment so **redux** should join the list of difficult packages on this platform: https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#what-if-cran-doesnt-provide-package-binaries-for-macos-yet

Thanks!

**Comment by hpages** [comment]
Thanks Jen.

About this: https://github.com/Bioconductor/BBS/blob/master/Doc/Prepare-macOS-Mojave-HOWTO.md#417-install-hiredis

Remember that we should avoid installing things via Homebrew _at all cost_ on the Mac builders, unless that's our only choice. In that case installing `hiredis` is not needed at all because we're using the "difficult package trick". 

This is actually the whole point of the "difficult package trick". In normal times the Mac binary package for **redux** is available on CRAN so no external libraries are needed to install this binary. But CRAN doesn't provide any Mac binary package _for R devel_ yet, so we use the "difficult package trick" to install the **redux** binary _for R release_. This trick avoids us having to install many external libraries that would otherwise be needed if we were trying to install all CRAN packages from source.

I can't emphasize enough the importance of reducing the use of brew at its strict minimum on the Mac builders. Unfortunately the setup of these machines is tricky and fragile, and brew is known to not play nice with it. This is why we want to keep the Mac builders as clean and stable as possible.

Let me know if you have questions of need help with this.

Thanks,
H.

**Comment by hpages** [comment]
I'm reopening so we don't forget

**Comment by hpages** [comment]
Yes. From all Mac machines where it was installed.

Also remove the "4.17 Install hiredis" section from the doc.

Thx

**Comment by jwokaty** [comment]
I reverted changes to the doc and `brew uninstall hiredis` from kjohnson2 and merida1 before  removing the existing redux then installing the 4.2 version of redux.

**Comment by hpages** [comment]
Thanks!
