### ISSUE TITLE
Cygwin - fatal error on Moscato1 when using ls

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#27]
The issue is that the PATH has C:\Rtools33\bin (which includes some items from MinGW and a particular version of a Cygwin DLL) before Cygwin's expected copy of these things.  We want to treat this bug very carefully, as the build system expects Rtools resources at the start of the PATH.  Interestingly, this bug doesn't affect Moscato2, so comparing might result in some useful information.

Here's a screenshot

![screenshot from 2015-11-25 09 33 25](https://cloud.githubusercontent.com/assets/66993/11399796/9813e894-9357-11e5-93a8-e33bde41f2b5.png)

**Comment by b-long** [comment]
Goal is to have Cygwin version match the DLL version that's included with Rtools.

**Comment by dtenenba** [comment]
Might be tricky to match the DLL version exactly, but in looking at moscato2, the version of cygwin1.dll is more recent than the one in rtools, so I decided to update the non-rtools cygwin on moscato1 and that resolved the issue; I can now run `ls` in the cygwin shell on moscato1 where before it was giving the error above.
