### ISSUE TITLE
Block propagation for a mac binary if dynamic links are bad

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#282]
In the build bin step for macs, dynamic links are changed from pointing to /opt/gfortran to the libraries in the binary with the `fix_dylib_links` script; however, sometimes the links aren't correct, such when the path to a library changes.  In https://github.com/Bioconductor/BBS/commit/6e5bcaccdf873cd52be172f4d742e6520d55b7a4 the paths are displayed before the script is run as well as the result; however, it would be useful to block bad binaries from being propagated. See #281 and https://github.com/Bioconductor/BBS/commit/6e5bcaccdf873cd52be172f4d742e6520d55b7a4.

**Comment by jwokaty** [comment]
From reading https://github.com/Bioconductor/BBS/blob/devel/utils/makePropagationStatusDb.R, it seems that propagation is based whether there's a newer version and if all dependencies are available and this is determined on one of the linux machines. For this issue, we need the status to be based on whether a bad path is encountered when `otool -L "$so_file"` is run on the mac.

**Comment by hpages** [comment]
As explained in our #buildsystem Slack channel (May 1st), there's no need to touch the propagation logic. Propagation simply won't happen if `BUILD BIN` fails, so `BUILD BIN` _should_ fail if `otool -L "$so_file"` outputs a bad path (right now it doesn't). In other words: `build-universal.sh` should take care of checking the output of `otool -L "$so_file"` and fail (i.e. return a non-zero value) if a bad path is found there. Then `BUILD BIN` will display an ERROR (as it should), and the package binary won't be allowed to propagate.

Makes sense?

**Comment by hpages** [comment]
Hi @jwokaty ,

It seems that PR #286 breaks `BBS/utils/build-universal.sh`. The script does not produce the binary anymore.

That's because `BBS/utils/build-universal.sh` _sources_ `BBS/utils/macosx-inst-pkg.sh`, so when the latter calls `exit`, this has the effect of exiting the former too. This means that  `BBS/utils/macosx-make-tgz.sh` (the script called by `BBS/utils/build-universal.sh` to actually make the binary tarball) does not get called.

The fix is simple. Instead of doing:
```
exit_code=0
...
...

if [ $exit_code -eq 1 ]; then
    echo ""
    echo "Error: Bad BBS configuration."
    echo "Bad library paths not corrected in macOS binaries. Contact the core team by filing an issue at https://github.com/Bioconductor/BBS/issues."
fi

exit $exit_code
```
`BBS/utils/macosx-inst-pkg.sh` should do:
 ```
bad_links=0
...
...

if [ $bad_links -eq 1 ]; then
    echo ""
    echo "Error: Bad BBS configuration."
    echo "Bad library paths not corrected in macOS binaries. Contact the core team by filing an issue at https://github.com/Bioconductor/BBS/issues."
    exit 1
fi
```

Thanks!
