### ISSUE TITLE
Remove Lock Files

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#289]
Occasionally, installation will be blocked by locked files. We need a mechanism to remove the locked files before or at the start of the run.

**Comment by hpages** [comment]
We already remove `LOCK` files at the start of the run on Linux and Mac: https://github.com/Bioconductor/BBS/blob/41e656b604729ac81db102932290091d890ad1c9/utils/clean-before-run.sh#L4

Looks like we don't do it on Windows (https://github.com/Bioconductor/BBS/blob/devel/utils/clean-before-run.bat), not sure why.

Note that `clean-before-run.sh` and `clean-before-run.bat` are called by `run.sh` and `run.bat`, respectively

I suspect that the `LOCK` files that we see occasionally on the Mac builders that get in the way get created during the INSTALL stage itself (STAGE2).

`LOCK` files are expected: `R CMD INSTALL` automatically creates them at the beginning of a package installation and removes them at the end, whether the installation was succesful or not. In other words, `R CMD INSTALL` should remove them no matter what. So we need to understand why sometimes a `LOCK` file gets in the way. One possible cause could be that 2 build runs are overlapping and are both trying to install the same package at the same time. Another reason could be that for some reason `R CMD INSTALL` dies before it has a chance to remove the `LOCK` file (e.g. BBS kills it after a TIMEOUT?). Another reason could be an issue with `R CMD INSTALL` itself where, under some circumstances, it does not or cannot remove the `LOCK` file. This will require some non-trivial detective work.

BTW, now that we install in `<R_HOME>/site-library/` on Linux, `clean-before-run.sh` should remove `LOCK` files from that folder too.

Thanks

**Comment by jwokaty** [comment]
There were locks recently on a mac arm64 builder (https://support.bioconductor.org/p/9152542/#9152543), so in that case it wasn't an overlap of builds. It might be related to a timeout; however, it should still remove the locks on the next run.

Maybe `rm -rf "$BBS_R_HOME/library/00LOCK"` should be changed to `rm -rf "$BBS_R_HOME/library/00LOCK*"`  with an asterisk since lock files are named `00LOCK-packageName` as in `/usr/local/lib/R/site-library/00LOCK-fgsea`?

**Comment by hpages** [comment]
Good catch! The `rm -rf "$BBS_R_HOME/library/00LOCK"` command is from the ancient times when `R CMD INSTALL` only supported a per-library lock file. Per-package lock files are more recent and I think they are used by default (contrary to `R CMD INSTALL --help` claim).

There's also the option to disable locking completely by using `R CMD INSTALL --no-lock` but I'm not too confortable with that.

Since you are on this, make sure to clean `<R_HOME>/site-library/` in addition to `<R_HOME>/library/`.

Thanks
