### ISSUE TITLE
Add Linux ARM64 builder as a node that participates to the BioC daily builds

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#292]
Hi @martin-g, @Yikun

As mentioned on our community Slack (#arm-linux channel) yesterday, your build machine will need to be configured as an  "external build node" for that. This is a first for us. Yesterday and today I worked on modifying BBS to support the new "external build node" case. Make sure to pull the latest version.

I also updated [`Prepare-Ubuntu-22.04-HOWTO.md`](https://github.com/Bioconductor/BBS/blob/devel/Doc/Prepare-Ubuntu-22.04-HOWTO.md) to document the specificities of the "external build node" setup. This is a lighter/simpler setup than for a _standalone_ builder. I believe that your machine is already set up as the latter so you don't have to change anything to your current setup. However, please check sections "2.5 Add software builds to biocbuild's crontab" and "2.6 First build report". This will probably be new for you.

Also your machine would need to be added to our nodes database (in `BBS/nodes/`), and build configuration files and scripts for it would need to be added to `BBS/3.18/bioc/`. More precisely, here are the changes that would need to be done to BBS:

1. Add your machine to our nodes database:

    This consists in adding a new entry for it to `BBS/nodes/nodespecs.py`. See the entry I added at the bottom of the file for fake "external node" xps15, and add a similar entry for your machine after it.

    You will also need to add a new subfolder in `BBS/nodes/` for your machine, with a `local-settings.sh`
file in it. See the `BBS/nodes/xps15/` subfolder for an example (adapt the paths in `local-settings.sh` to reflect where things are on your machine).

2. Add build configuration files and scripts for your machine:

    This consists in adding a new subfolder for your machine in `BBS/3.18/bioc/`. See the `BBS/3.18/bioc/xps15/` subfolder for an example and adapt.

Please submit a PR whenever this is ready.

Finally, once your machine is properly set up and was able to complete its first build run as an "external node", we will need to discuss a way for us to retrieve the content of the `~/bbs-3.18-bioc/products-out/` folder from it. This is where BBS will drop all the build products during the builds. We'll need to be able to access this daily in order to include your build results in our daily report. This could typically be done via `rsync` i.e. think of `~/bbs-3.18-bioc/products-out/` as something that we'd like to be able to mirror on our central builder.

Thanks for helping Bioconductor improve its support for Linux ARM64.

Let me know if you have questions.

Best,
H.

**Comment by Yikun** [comment]
@hpages Thanks for your effort and help! We will submit the PR when everthing is ready!

**Comment by martin-g** [comment]
PR: https://github.com/Bioconductor/BBS/pull/293

**Comment by hpages** [comment]
First Bioconductor daily report with kunpeng2 results: https://bioconductor.org/checkResults/3.18/bioc-LATEST/long-report.html

**Comment by jwokaty** [comment]
Is this issue complete and ready to close?

**Comment by martin-g** [comment]
It is OK to be closed!
We have opened some PRs to specific packages but there is nothing to improve in BBS itself!

**Comment by hpages** [comment]
Great. Let's close then.
