### ISSUE TITLE
_SP_EVOLUTION_STATUS_=2

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#294]
`rgdal, rgeos and maptools` will be archived by CRAN in October 2023.

- [x] Add flag `_SP_EVOLUTION_STATUS_=2` to use `sf` rather than `rgdal`.
- [x] Additionally, check if any documentation mentions the CRAN packages that will be removed.

It might be helpful to add a note in the build linking to r-spatial.org.

See 

* https://r-spatial.org/r/2023/05/15/evolution4.html
* https://stat.ethz.ch/pipermail/bioc-devel/2023-June/019727.html

**Comment by jwokaty** [comment]
@hpages Could I just ask for a second opinion on this flag?

After reading https://r-spatial.org/r/2023/05/15/evolution4.html, they will make this behavior the default this month in June. Furthermore the behavior seems to only help packages using `sp` that use `rgdal` but not `rgeos`. Although `sp` is on our builders, `rgdal` is not, so I think no package would benefit from this flag. `rgdal` is not a dependency for any Bioconductor package.

Of course, someone could submit a package that does, but I think we just need to update `sp` when it is updated on CRAN to have the new behavior.

However, we do have packages with

* `rgeos` listed as a dependency: flowDensity.
* `maptools` listed as a dependency or imports: GateFinder, GEOExplorer

I have sent them emails.

**Comment by hpages** [comment]
Thanks for notifying the **flowDensity**, **GateFinder**, and **GEOExplorer** folks. I'm not sure I fully understand what `_SP_EVOLUTION_STATUS_=2` does exactly or what benefit we'd get from setting this on the build machines. Maybe ask Kasper for clarifications since he suggested this on Slack? (#tech-advisory-board channel)
