### ISSUE TITLE
Remove rgeos and maptools from builders

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#300]
CRAN will archive rgeos, maptools, rgdal October 2023: https://stat.ethz.ch/pipermail/r-packages/2023/001825.html. The following packages import or declared one of these as a dependency and were initially contacted June 2023:

* GEOExplorer
* GateFinder
* flowDensity

As of June 2023, rgdal isn't installed on the builders; however, rgeos and maptools are, but they should be removed before the release.

**Comment by hpages** [comment]
Looks like on Oct 16, **rgeos** and **maptools** finally got removed from CRAN and archived (see https://cran.r-project.org/package=rgeos and  https://cran.r-project.org/package=maptools), so should be removed from the build machines ASAP (3.18 machines only, I don't think the 3.19 machines have them).

**Comment by jwokaty** [comment]
@martin-g We've removed `rgeos` and `maptools` from our 3.18 builders. I recommend removing them on kunpeng2 as well.
