### ISSUE TITLE
Add note to doc about the active hours setting on Windows

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BBS#305]

**Comment by hpages** [comment]
Thanks @jwokaty! BTW I just noticed the  2.4 section (right above the section you just added):

https://github.com/Bioconductor/BBS/blob/f87de6f9b752c653e2b52914635cca4c4deb78c9/Doc/Prepare-Windows-Server-2022-HOWTO.md?plain=1#L647-L678

Just went on palomino3 to check if this feature was still available in Windows Server 2022, but I couldn't find it. It's probably been removed. I guess it's called progress :disappointed:

**Comment by jwokaty** [comment]
Thanks. I've opened #307 to remove it.
