### ISSUE TITLE
Implement log rotation

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#33]
For *nix, we can use [`logrotate`](https://www.digitalocean.com/community/tutorials/how-to-manage-log-files-with-logrotate-on-ubuntu-12-10) and for Windows we can use [LogRotateWin](http://sourceforge.net/projects/logrotatewin/).

**Comment by vobencha** [comment]
Not sure which logs this issue is referring to or if the problem was addressed since opened. System and application logs are currently rotated on the builders. Build logs in /home/biocbuild/bbs-*/log/ are removed with each release.

Issue no longer seems relevant.
