### ISSUE TITLE
Remove libcudart10.1 for ubuntu 22.04

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#335]
I don't think this is needed for Ubuntu 22.04 (it's also not available).

**Comment by hpages** [comment]
Looks like it's been replaced with `libcudart11.0` in Ubuntu 22.04:
```
hpages@nebbiolo1:~$ apt-cache search libcudart
libcudart11.0 - NVIDIA CUDA Runtime Library
```
Not needed for the builds, but can be installed to avoid an annoying tensorflow warning (as explained in the doc). Also not listed in any of the `Ubuntu-files/22.04/apt_*.txt` files. So it's really just an FYI in the doc.
