### ISSUE TITLE
Remove recently archived CRAN packages from devel builders

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#359]
https://cran.r-project.org/web/packages/assertive/index.html

**Comment by hpages** [comment]
Other packages that got removed from CRAN that affect us:
- **norm2**:  https://cran.r-project.org/package=norm2
- **corncob**:  https://cran.r-project.org/package=corncob
- **uchardet**:  https://cran.r-project.org/package=uchardet

Note that we should also update kjohnson1 to R 4.3.2 so no need to remove anything there.

Thx!

**Comment by jwokaty** [comment]
Is there some process you used to figure out what dependencies were archived? I am waiting on the actual release for M1 as it is still the RC version.

**Comment by hpages** [comment]
Just spotted another one (archived on 2023-10-24):
- **multipanelfigure**: https://cran.r-project.org/package=multipanelfigure. Breaks **celda** + indirectly **decontX** and **singleCellTK**.

> Is there some process you used to figure out what dependencies were archived?

Just poking around https://bioconductor.org/checkResults/3.19/bioc-LATEST/long-report.html and looking at merida1-only errors.

> I am waiting on the actual release for M1

Seems to have landed (or taken off? :rocket: ): https://cran.r-project.org/bin/macosx/

**Comment by hpages** [comment]
One more (archived on 2023-10-29):
- **rbokeh**: https://cran.r-project.org/package=rbokeh. Breaks **SeqSQC**.

Darn, it's almost like CRAN decided to remove stuff right after we made a new release! :upside_down_face:

**Comment by hpages** [comment]
One more (archived on 2023-07-09):
- **rsnps**: https://cran.r-project.org/package=rsnps. Breaks **appreci8R**.

That should be all for now.

**Comment by jwokaty** [comment]
> Seems to have landed (or taken off? 🚀 ): https://cran.r-project.org/bin/macosx/

Thanks. I always check mac.r-project.org, which currently shows RC.

Thanks for keeping track of the packages. Should we follow up with maintainers?

**Comment by lshep** [comment]
FWIW: MsCoreUtils, benchdamic and MMAPPR2 responded.  autonomics/multicrispr and RCy3 have not responded.  But those maintainers have been contacted already.

**Comment by hpages** [comment]
> Thanks. I always check mac.r-project.org, which currently shows RC.

That's not the right place to check for an official R release.

**Comment by jwokaty** [comment]
> That's not the right place to check for an official R release.

Noted. All release builders are updated.

**Comment by hpages** [comment]
> Is there some process you used to figure out what dependencies were archived?

@jwokaty FWIW here is a little function you can use to find those CRAN packages that are installed on a builder but have vanished from CRAN:
```
find_vanished_CRAN_pkgs <- function(CRAN_repos="https://cran.r-project.org") {
    inst_pkgs <- installed.packages()[ , "Package"]
    is_cran <- sapply(inst_pkgs, function(pkg) "CRAN" %in% packageDescription(pkg)$Repository)
    inst_cran_pkgs <- inst_pkgs[is_cran]
    all_cran_pkgs <- available.packages(repos=CRAN_repos)[ , "Package"]
    setdiff(inst_cran_pkgs, all_cran_pkgs)
}
```
Returns the following on nebbiolo1:
```
> find_vanished_CRAN_pkgs()
 [1] "assertive.code"       "assertive.data"       "assertive.data.uk"   
 [4] "assertive.data.us"    "assertive.datetimes"  "assertive.properties"
 [7] "assertive.strings"    "assertive.types"      "multipanelfigure"    
[10] "optimr"               "rbokeh"               "Rcgmin"              
[13] "Rvmmin"              
```
We should probably think about having BBS automatically remove vanished packages (+ their rev deps) at the beginning of a run.

**Comment by jwokaty** [comment]
- [x] Check Ubuntu-files for dependencies related to removed CRAN packages
