### ISSUE TITLE
Update packages to install via Homebrew

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#374]
A few difficult packages that aren't available in Simon's binaries should be installed via Homebrew. Two that work after Homebrew installation are hiredis and mariadb-connector-c; however, a few others don't seem to work, even after making symlinks from the pkg-config files in the Cellar to `/opt/homebrew/lib/pkgconfig` on arm64. (We didn't do this on x86_64, so maybe the arm64 binaries are behind the x86_64 or the paths are different?)

After attempting to install difficult packages and also brew installing dependencies, we fail to install `archive`, `av`, `proj4`, `rsvg`, `units`, lwgeom`, `sf`.

(Note: Also unable to install `Rmpfr`, 'terra' -- these seem to have a link issue)

**Comment by hpages** [comment]
Can you provide some details on the problems/errors you get when trying to install the difficult packages using [the trick documented here](https://github.com/Bioconductor/BBS/blob/devel/Doc/Prepare-macOS-Big-Sur-HOWTO.md#what-if-cran-doesnt-provide-package-binaries-for-macos-yet)?

FWIW using this trick seems to work fine for **archive** on kjohnson3:
```
contriburl <- "https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3"

install.packages("archive", contriburl=contriburl)
# trying URL 'https://cran.r-project.org/bin/macosx/big-sur-arm64/contrib/4.3/archive_1.1.5.tgz'
# Content type 'application/x-gzip' length 1531678 bytes (1.5 MB)
# ==================================================
# downloaded 1.5 MB
# 
# The downloaded binary packages are in
# 	/var/folders/kj/tw9rgy0j1nv62ttkz2z2wqcm0000gt/T//RtmpsHMQzC/downloaded_packages

library(archive)  # successful load
```
Note that the advantage of using  this trick is that we still install package binaries so we don't need Simon's binaries or additional Homebrew installs.

**Comment by jwokaty** [comment]
I see in looking back on my most recent attempt, I had an error in my code when I tried to install it before I wrote this since I was just testing it individually. They seem to be installing fine. I'll close this after I finish installing everything.
