### ISSUE TITLE
Link to Troubleshooting Build Report broken

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/BBS#381]
Hi,

the `Troubleshooting Build Report` link to the help page in a build report (for example https://master.bioconductor.org/checkResults/3.18/bioc-LATEST/tRNAdbImport/nebbiolo2-buildsrc.html) is broken.

It reads `https://master.bioconductor.org/checkResults/3.18/bioc-LATEST/tRNAdbImport/%s`

**Comment by hpages** [comment]
@jwokaty Can you take a look? Looks like a regression introduced at commit caf91bcf5fc4c49843c855a14696027bf27a159e

**Comment by jwokaty** [comment]
I'll submit a PR. Thanks @FelixErnst for reporting this!
