### ISSUE TITLE
Cargo, rustc for clarabel

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#419]
BioC ANCOMBC depends on CRAN CVXR, which depends on CRAN clarabel, which has system dependencies rustc and cargo.

- [ ] Add to https://github.com/Bioconductor/BBS/blob/devel/Ubuntu-files/22.04/apt_cran.txt
- [ ] Install nebbiolo2 (I believe it's there already)

See https://cran.r-project.org/web/packages/clarabel/index.html and https://github.com/Bioconductor/BBS/issues/180

**Comment by martin-g** [comment]
I'll make sure they are installed on kunpeng2 too!

**Comment by martin-g** [comment]
> I'll make sure they are installed on kunpeng2 too!

Done!
