### ISSUE TITLE
No need for continuation characters

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#42]
Remove the continuation from : 
- [nodespecs.py](https://github.com/Bioconductor/BBS/blob/feature/migrate_back_to_hutch/nodes/nodespecs.py#L14-L188) (continuation on 174 lines, assuming my grep foo is correct)
- [BBScorevars.py](https://github.com/Bioconductor/BBS/blob/feature/migrate_back_to_hutch/BBScorevars.py#L89-L96) (another handful)

**Comment by b-long** [comment]
@dtenenba When you have a moment, can you review the open PR ?  ( #49 )

**Comment by dtenenba** [comment]
I assume you are syntax checking these files (`python -m py_compile filename.py`) before committing?

**Comment by b-long** [comment]
@dtenenba Yes, that's correct, both are syntactically correct.
