### ISSUE TITLE
  X11 nebbiolo2

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#428]
On nebbiolo2:
> capabilities()["X11"]
  X11 
FALSE 
> X11()
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In X11() : unable to open connection to X11 display ''
This causes the following error on the 3.20 report: https://bioconductor.org/checkResults/3.20/bioc-LATEST/adSplit/nebbiolo2-checksrc.html (there could be other packages affected). (edited) 

May be resolved by recompiling R. Need to install the new R too.

**Comment by hpages** [comment]
More likely to be a problem with the Xvfb setup.

For example `R/bin/Rscript -e 'png("fig2.png", type="Xlib")'` works on nebiolo1, but not on nebbiolo2:
```
biocbuild@nebbiolo2:~/bbs-3.20-bioc$ R/bin/Rscript -e 'png("fig2.png", type="Xlib")'
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: png
In addition: Warning message:
In png("fig2.png", type = "Xlib") :
  unable to open connection to X11 display ''
Execution halted
```
Also `service xvfb status` reports some anomalies on nebbiolo2:
```
biocbuild@nebbiolo2:~$ service xvfb status
Warning: The unit file, source configuration file or drop-ins of xvfb.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● xvfb.service - LSB: Loads X Virtual Frame Buffer
     Loaded: loaded (/etc/init.d/xvfb; generated)
     Active: active (exited) since Wed 2024-10-09 11:57:21 EDT; 3 weeks 1 day ago
       Docs: man:systemd-sysv-generator(8)
        CPU: 1min 54.415s

Warning: some journal files were not opened due to insufficient permissions.
```
compared to nebbiolo1:
```
biocbuild@nebbiolo1:~$ service xvfb status
● xvfb.service - LSB: Loads X Virtual Frame Buffer
     Loaded: loaded (/etc/init.d/xvfb; generated)
     Active: active (running) since Thu 2024-10-31 06:54:34 EDT; 8h ago
       Docs: man:systemd-sysv-generator(8)
    Process: 501840 ExecStart=/etc/init.d/xvfb start (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 153968)
     Memory: 15.7M (peak: 26.2M swap: 6.3M swap peak: 10.4M)
        CPU: 11.239s
     CGroup: /system.slice/xvfb.service
             └─501845 /usr/bin/Xvfb :1 -screen 0 800x600x16
```

**Comment by jwokaty** [comment]
Ok, I'll try to set up xvfb again tomorrow when the builds aren't running.

**Comment by hpages** [comment]
Sounds good. Also it seems that the machine requires a restart. I recommend you do that first.

**Comment by jwokaty** [comment]
Restarting xvfb seemed to resolve the issue. Everything appeared set up correctly. Now `R CMD check` doesn't produce a warning for `Moonlight2R` and `capabilities()["X11"]` is `TRUE`.

**Comment by hpages** [comment]
Great. Don't forget to restart nebbiolo2 when you get a chance. Would be good to check the xvfb service again right after the reboot, just to make sure that the problem we had was not caused by the xvfb service not starting properly in the context of the boot sequence. Thanks!
