### ISSUE TITLE
Allow ForceInstall in .BBSoptions

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BBS#44]
Needed when a software package without reverse dependencies Suggests: a data experiment package, and data experiment package Depends: on software package. The software package will not be forced to be installed because it has no reverse dependencies, and it will fail to build because of the missing  data experiment package.

Why will the data experiment package fail to build?

**Comment by mtmorgan** [comment]
Commit https://github.com/Bioconductor/BBS/commit/e08e6b07f34083e549180b4eb992732f725e005d uses read.dcf. Commit https://github.com/Bioconductor/BBS/commit/87f9cd56928f3ba6ec39ddf29b45ad4d40483106 revises. BUT the .BBSoption files are not valid dcf, demonstrated by the following, where "~/b/Rpacks" is an svn checkout of the current software directory

```
path = "/home/mtmorgan/b/Rpacks"
setwd(path)
Sys.setenv("BBS_MEAT_PATH"=path)
.getPkgsToForceInstall(dir())
````

which returns

```
> .getPkgsToForceInstall(dir())
ERROR make_STAGE2_pkg_deps_list
  filePath: /home/mtmorgan/b/Rpacks/Biostrings/.BBSoptions
  condition: Line starting '# Default value for  ...' is malformed!TRUE
ERROR make_STAGE2_pkg_deps_list
  filePath: /home/mtmorgan/b/Rpacks/dupRadar/.BBSoptions
  condition: Line starting '# Default value for  ...' is malformed!TRUE
ERROR make_STAGE2_pkg_deps_list
  filePath: /home/mtmorgan/b/Rpacks/QuasR/.BBSoptions
  condition: Line starting '# The reason this is ...' is malformed!TRUE
ERROR make_STAGE2_pkg_deps_list
  filePath: /home/mtmorgan/b/Rpacks/Rbowtie/.BBSoptions
  condition: Line starting '# The reason this is ...' is malformed!TRUE
ERROR make_STAGE2_pkg_deps_list
  filePath: /home/mtmorgan/b/Rpacks/Rsubread/.BBSoptions
  condition: Line starting '# Default value for  ...' is malformed!TRUE
[1] "Chicago
```

**Comment by jimhester** [comment]
Another option would be simply stripping the comment lines prior to calling `read.dcf`

```r
read.dcf(grep("^#",  x, invert = TRUE, value = TRUE)) 
```

**Comment by dtenenba** [comment]
@jimhester `read.dcf()` takes a file as its first argument, not a character vector.

**Comment by dtenenba** [comment]
@mtmorgan f6be525d35b9d339b9719a64391ad17db979837c modifies the original branch to not use read.dcf at all, just parse the file.

**Comment by mtmorgan** [comment]
700f15c04de2346a05c5d30cff3064c99e966d0a closes.
