### ISSUE TITLE
Archive all pushed package versions

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BBS#45]
Currently, only the final version of a package in a Biocondcutor release is archived. The archived version is in the CRAN-style archive for each Bioconductor release, but difficult to locate if one has only the package version number.

Possibilities include archiving each pushed version (on the release branch only, to save space? but we haven't calculated how large a full archive would be) or to tag pushed versions within svn / git.

Discussed several times, including on the support site [[1](https://support.bioconductor.org/p/75927/)] and Bioc-devel [[2](https://stat.ethz.ch/pipermail/bioc-devel/2015-November/008343.html)]

**Comment by vobencha** [comment]
Packages are now archived for each release:
https://bioconductor.org/packages/3.6/bioc/src/contrib/Archive/
