### ISSUE TITLE
Build report should indicate package deprecation status

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BBS#46]
Packages (such as CausalR in release) that are deprecated have `PackageStatus: Deprecated` in their DESCRIPTION file. The build report (view of all packages) should indicate deprecated packages visually somehow so that we don't always have to stop and figure out why the package is broken.

**Comment by b-long** [comment]
For anyone interested, the following packages are currently deprecated : 
- CausalR
- DAVIDQuery
- GenoView

**Comment by dtenenba** [comment]
Closed by f409bd504427a99592e54ac2b6c96d48ff27f767 .
