### ISSUE TITLE
stagger the uptime of cytoscape3 docker containers

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BBS#53]
Instead of having ~10 containers running at once which will run out of memory, add hooks to RCy3 package which will trigger the container to come on when needed (and it will automatically get shut off after a certain period).

**Comment by dtenenba** [comment]
Actually it might be better to have hooks at the build system level, to trigger events before and after certain BBS phases (buildsrc and checksrc). These could probably be declared in .BBSoptions.

**Comment by vobencha** [comment]
Closing this issue because we no longer use dockers on the build system.
