### ISSUE TITLE
refactor report code to use templates

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BBS#54]
The code that generates the build report (BBS-report.py et al) might be a lot easier to understand and maintain if it used templates (probably jinja2) instead of writing out every bit of HTML.

**Comment by dtenenba** [comment]
some progress on this in https://github.com/Bioconductor/BBS/tree/refactor/report_templates ; starting with the easy ones. ;)

**Comment by hpages** [comment]
replaced with #290
