### ISSUE TITLE
'packages with impossible dependencies' are still propagating

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/BBS#57]
...despite work done to supposedly prevent this.

Example: the package `prada` has not built in devel (as of 2/2/2016). 
It installs but fails check.

There are several packages that depend on or import `prada`: 

```
domainsignatures, facsDorit, RNAither 
cellHTS, cellHTS2
```

However, these packages are propagating and do not have the 'red light' in the build report.

**Comment by dtenenba** [comment]
@vobencha @mtmorgan

**Comment by hpages** [comment]
[createPropagationDB.R](https://github.com/Bioconductor/BBS/blob/master/utils/createPropagationDB.R) got replaced with [makePropagationStatusDb.R](https://github.com/Bioconductor/BBS/blob/master/utils/makePropagationStatusDb.R) (new implementation from scratch) in May 2021.

The new code doesn't seem to have the problem reported in this issue (at least nothing like this has been observed or reported so far).
