### ISSUE TITLE
Consistent use of `,` in 'stoplights'

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BBS#64]
Messages for 'stoplights' describing package propagation mostly use format `TAG, explanation`, e.g., `YES, new version is higher than...` but a few places, e.g., https://github.com/Bioconductor/BBS/blob/42918442c5df42c1d91c43630e2a273044b05af1/utils/createPropagationDB.R#L156 and later at line 170 use `NO: ...` with a `:` instead of `,`. Maybe these should be consistent, always using `,`.

**Comment by hpages** [comment]
@mtmorgan 
This got addressed in May 2021 when [createPropagationDB.R](https://github.com/Bioconductor/BBS/blob/master/utils/createPropagationDB.R) got replaced with [makePropagationStatusDb.R](https://github.com/Bioconductor/BBS/blob/master/utils/makePropagationStatusDb.R) (new implementation from scratch).
