### ISSUE TITLE
rjava not available in merida2

### ISSUE THREAD

**Issue by aravind-j** [Bioconductor/BBS#68]
`rjava` is not available in the _merida2_ build system (OS X 10.11.6 El Capitan/x86_64) resulting in [build error](http://bioconductor.org/spb_reports/rmelting_buildreport_20190116053524.html)s (Bioconductor/Contributions#973).

**Comment by lshep** [comment]
The CRAN package MAC binary for R-3.6.0 has not be generated yet as indicated on the [rJava landing page](https://cran.r-project.org/web/packages/rJava/index.html)  Once the binary becomes available it will be added to _merida2_  .  Until it is generated by CRAN there is nothing for us to do.  Your package reviewer is aware of this and can ignore that platform for now.
