### ISSUE TITLE
Guaranteeing vignette link integrity in workflows

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BBS#69]
A few weeks ago, @robertamezquita and I were talking about integrating his OSCA book with my _simpleSingleCell_ workflow. We concluded that attempting a tight integration would only end in tears for the both of us, given the different scope of the two projects (OSCA focuses on introducing Bioconductor infrastructure in a single-cell context, _simpleSingleCell_ just goes straight into the applications), differences in organization and format, coding style, etc.

Instead, we decided that the best way to naturally encourage integration would be to insert links to each other's workflows in our own workflows. This would improve discoverability between our workflows as readers could easily move between them where appropriate. It would also promote consistency in the information being conveyed as we or readers will be more easily able to spot contradictions in our messages (and complain about it on the support site).

Currently, this inter-linking is achieved via the `BiocStyle::Biocpkg()` package and its friends. I have no problem with this, but for the strategy above to be useful to readers, we have to ensure that the links are live. In the current build system for workflows, there is no protection against dead links in the compiled vignettes. `R CMD check --as-cran` checks for dead links, so turning on `check` for workflows seems like an easy fix. (Package functionality should be minimal, and we can just skip the workflow rebuilding, so there should be effectively no additional burden on the build system.) Alternatively, if `--as-cran` is unpalatable, we could just take the part that checks the links and run it in isolation.

Another related consideration is whether the validity of HTML anchors can be checked. This is almost as important as the check for the validity of the link itself, as some of my workflows are quite long. A link pointing to the correct workflow but an invalid anchor would just open the workflow page at the top and require the user to guess the relevant section - not trivial when there's ~10 sections. I actually don't know whether `R CMD check` is smart enough to detect anchor validity - I would guess not.

I have some more outlandish ideas about using the build system to scrape Bioconductor URLs from vignettes; build an index of links across all packages and vignettes; and provide a kind of on-hover "Suggestions" box for each section title in the vignette to show incoming links. This means that if Rob adds a link to my workflow, I wouldn't have to manually add a reciprocal link back to Rob's stuff; it's automagically done. Unfortunately, I don't know enough Javascript to do that.

**Comment by hpages** [comment]
Hi @LTLA,

If you are still listening and still care about this, do you happen to know which `_R_CHECK_*` env variable controls the checking of dead links in compiled vignettes during `R CMD check`? So far we've been reluctant to use `R CMD check --as-cran` on our build machines but my understanding is that using it is equivalent to defining a bunch of `_R_CHECK_*` env variables but what "bunch" exactly doesn't seem to be documented. If we knew which one controls the checking of dead links then we could simply add it to the [set of variables that we already define on the build machines](https://github.com/Bioconductor/BBS/blob/master/3.16/Renviron.bioc).

But wait... major problem is that we don't run `R CMD check` for the workflow and book builds, only `R CMD INSTALL` and `R CMD build` there:

https://bioconductor.org/checkResults/3.15/workflows-LATEST/
https://bioconductor.org/checkResults/3.15/books-LATEST/

so making this work is probably going to be more complicated than that :disappointed:

Adding @jwokaty to this conversation.

Note that ideally we'd want to come up with a solution that is transparent (and not too hacky) so people can reproduce what they see on the build reports. Also it seems that there's no reason a priori to do this only for workflows or books.

H.

**Comment by LTLA** [comment]
Oh. I long forgot about this. We side-stepped the issue by just merging the **simpleSingleCell** workflows into the book; the various subbooks (via **rebook** and **knitr**) manage the correctness of their own links.

Guess it wouldn't hurt to check it in general, but I don't know the appropriate envvar to do so.

**Comment by hpages** [comment]
Then I'd say let's just close this. I'm not sure there's an easy way to check for dead links in compiled vignettes besides using `R CMD check --as-cran`.
