### ISSUE TITLE
Jobs sometimes do not timeout

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#7]
Currently, there are 2 mechanisms to ensure that a build does not take a very long time :

1. The function at line [#156 of jobs.py](https://github.com/Bioconductor/BBS/blob/master/bbs/jobs.py#L156) (a part of the build system) will kill a build if one phase takes longer than 40 minutes.
2. The second is [killproc.py](https://github.com/Bioconductor/BBS/blob/master/utils/killproc.py) which runs via cron, ensures that a job does not take longer than 4 hours in aggregate.

In some cases (such as recently on linux2.bioconductor.org), neither of these catch a long-running job.  We need to investigate this and resolve the problem.  It should be the case that the process has permission to kill the long running job, since everything (the build system and cron jobs) should run as the `biocbuild` user.

cc @dtenenba

**Comment by b-long** [comment]
Should have said this earlier, this issue is not affecting Windows or Mac as far as we know.  It is only affecting Linux.  So in terms of the execution of jobs.py, we can isolate to [line #160](https://github.com/Bioconductor/BBS/blob/master/bbs/jobs.py#L160).

**Comment by dtenenba** [comment]
@b-long I made a commit to  killproc.py  (https://github.com/Bioconductor/BBS/commit/ac80ba11b1a48611b91f5e19aabf6bd7f1bbc515) that may partially address this, though of course we should figure out why the first line of defense is not working.

Looking at the error log I see that the script was failing before it even attempted to kill the process, on a line (https://github.com/Bioconductor/BBS/blob/ac80ba11b1a48611b91f5e19aabf6bd7f1bbc515/utils/killproc.py#L27-L29) where it was just trying to print out some information about the process. That was throwing an AccessDenied exception. I now catch that exception and indicate that the information could not be printed, but the script continues and will hopefully be able to kill the process.

**Comment by b-long** [comment]
Just commented on https://github.com/Bioconductor/BBS/commit/ac80ba11b1a48611b91f5e19aabf6bd7f1bbc515#commitcomment-13671611 .

**Comment by b-long** [comment]
Overcome by events.
