### ISSUE TITLE
Use compression to send files from Seattle to Virginia

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#8]
Currently, we believe that the Mac builds (specifically on [perceval](http://bioconductor.org/checkResults/3.2/bioc-LATEST/perceval-NodeInfo.html)) might take a very long time because data is being sent from Seattle to Virginia (AWS east region).  We are considering two approaches to improve performance of this data transfer, namely : 

1. Using `rsync`'s built-in GZIP compression ([`--compress`](http://linux.die.net/man/1/rsync))
2. Using a [UDT wrapper for rsync](https://github.com/LabAdvComp/UDR)

cc @dtenenba

**Comment by b-long** [comment]
NB: We believe [`BBS_RSYNC_CMD`](https://github.com/Bioconductor/BBS/search?utf8=%E2%9C%93&q=BBS_RSYNC_CMD&type=Code) is responsible for the invocation of rsync.

**Comment by dtenenba** [comment]
Yes, `BBS_RSYNC_CMD` is defined for each node, here's where it is defined for linux1:
https://github.com/Bioconductor/BBS/blob/start-linux1/nodes/linux1.bioconductor.org/local-settings.sh#L14
The actual flags that are passed to rsync are set elsewhere in the BBS code; we need to find them.

This is still probably a good idea and we should pursue it, but I am optimistic that other actions will also help with this issue, specifically, swapping in the machine petty which is currently being used in the release (3.1) builds which will stop tomorrow. That machine has twice the number of cores so it should finish building faster than perceval does. It also does not have RAID issues as perceval does. Downside is the CPU it does have is slightly slower than perceval's and there is less disk space, but it ought to be ok. This machine will only be in use for another 6 months and then we can retire it.

**Comment by b-long** [comment]
No longer relevant.
