### ISSUE TITLE
Document & automate usage of special directories

### ISSUE THREAD

**Issue by b-long** [Bioconductor/BBS#9]
The BBS automatically pulls packages from the following folders on `linux1.bioconductor.org` : 

```
biocbuild@linux1:~/bbs-3.2-bioc/MEAT0
biocbuild@linux1:~/bbs-3.2-data-experiment/MEAT0
```

These folders are configured as a part of the release process.  There is mention of this in the documentation (without detail)  : https://github.com/Bioconductor/BBS/blob/master/Doc/prerelease_and_release_checklist.txt#L144

However, this should be explicit (and in the long term much of this should be automated).  The following steps should be taken toward the goal of increased maintainability : 
1. Explicitly call out the steps needed as a part of the release process:
   1. Explicitly say each step involved in moving and configuring resources (`mv x y` and `svn co foo`)
2. Create a shell script doing the manual steps; which replaces the manual task of `mv x y` and `svn co foo`.
   1. Use variables; rather than saying `cd ~/bbs-3.2-bioc`, an administrator should be able to do `cd "$BBS_CURRENT"`.  
      1. An environment variable such as this may not already exist, but the string is likely used used in other places.  If the environment variable does not exist, we need to determine the canonical place to configure the machine (automatically) with a variable like `BBS_CURRENT="bbs-3.2-bioc"` 
3. Lint all shell scripts using shellcheck upon every commit.  An example of automating this is done in the [Travis CI configuration for my ServiceMonitoring module](https://github.com/b-long/ServiceMonitoring/blob/master/.travis.yml#L7).
4. Use the shell script to perform the tasks mentioned in the [prerelease_and_release_checklist.txt](https://github.com/Bioconductor/BBS/blob/master/Doc/prerelease_and_release_checklist.txt#L144)
   1. In the short term, and administrator can run the script
   2. In the long term, an automated process can run the script
##### Note:

_I realize the above is a big target and we won't expect to complete this work right away_.  However, item 3 is rather easy and we can begin integrating processes like automated testing into parts of Bioconductor when time permits.

cc @dtenenba

**Comment by b-long** [comment]
Adding the label _bug_ as this is a bug in the documentation currently.  Will adjust (change to enhancement) as we work through the various steps above.

**Comment by b-long** [comment]
Currently not an issue we need to address.  If a solution is devised, it'd be better to use a portable language (e.g. Ruby / Python), rather than shell scripts.

**Comment by vobencha** [comment]
Issue should have been closed with comment https://github.com/Bioconductor/BBS/issues/9#issuecomment-171386769.
