### ISSUE TITLE
Remove Python packages

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#93]
Looking at https://github.com/Bioconductor/BBS/blob/master/Ubuntu-files/20.04/pip_pkgs.txt, I noticed we have names of old packages no longer in Bioconductor, like MOFA. We don't currently have CChIPRep and netReg in release. We should at least remove MOFA in the comments. For the others, @hpages do you think we can remove these as dependencies? 

Remove `tensorflow_probability` since `netReg` was deprecated in 3.13.

**Comment by hpages** [comment]
Absolutely.

I don't know what happened to **phmed**: it's in devel but not in release, and the landing page says it's been in Bioconductor since BioC 3.9 so it's not that it got recently accepted and added to devel.

Thanks!

**Comment by hpages** [comment]
Oh but that's because it's **phemd**, not **phmed**! There's no **phmed** package. **phemd** has been in Bioconductor since BioC 3.9 and is still in release and devel.

H.

**Comment by jwokaty** [comment]
Thanks for catching that!
