### ISSUE TITLE
Make build more robust to encoding problems

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/BBS#94]
Try to make bbs.parse.parse_DCF() robust to ISO-8859 encoding. In addition, when bbs.parse.parse_DCF() fails (for whatever reason), it should not be a fatal error. Instead the problematic package should be put in skipped-index.dcf.

**Comment by hpages** [comment]
First part (try to make `bbs.parse.parse_DCF()` robust to ISO-8859 encoding) is addressed by commit 319176a.

I think that with this fix, the second part becomes moot. If you look at `_add_or_skip_or_ignore_package()` in `BBS-prerun.py`, it seems that the 2 ways that `bbs.parse.parse_DCF()` can still fail are covered (`FileNotFoundError` and `bbs.parse.DcfParsingError` exceptions are caught). Or is there another way that `bbs.parse.parse_DCF()` could still fail?
